#ifndef PROVIDERS_H
#define PROVIDERS_H

#include "providers/StreamProvider.h"

#include "providers/AdjacentDifference.h"
#include "providers/AdjacentDistinct.h"
#include "providers/Concatenate.h"
#include "providers/CycledContainer.h"
#include "providers/Difference.h"
#include "providers/Distinct.h"
#include "providers/DropWhile.h"
#include "providers/Empty.h"
#include "providers/Filter.h"
#include "providers/FlatMap.h"
#include "providers/Generate.h"
#include "providers/Group.h"
#include "providers/Intersection.h"
#include "providers/Iterate.h"
#include "providers/Iterator.h"
#include "providers/Map.h"
#include "providers/Merge.h"
#include "providers/PartialSum.h"
#include "providers/Peek.h"
#include "providers/Repeat.h"
#include "providers/Singleton.h"
#include "providers/Slice.h"
#include "providers/Sort.h"
#include "providers/Stateful.h"
#include "providers/SymmetricDifference.h"
#include "providers/TakeWhile.h"
#include "providers/Union.h"
#include "providers/Zip.h"

#endif
