#ifndef SCHEINERMAN_STREAM_PROVIDERS_H
#define SCHEINERMAN_STREAM_PROVIDERS_H

#include "StreamProvider.h"

#include "AdjacentDifference.h"
#include "AdjacentDistinct.h"
#include "Concatenate.h"
#include "CycledContainer.h"
#include "Difference.h"
#include "Distinct.h"
#include "DropWhile.h"
#include "DynamicGroup.h"
#include "DynamicOverlap.h"
#include "Empty.h"
#include "Filter.h"
#include "FlatMap.h"
#include "Generate.h"
#include "Group.h"
#include "Intersection.h"
#include "Iterate.h"
#include "Iterator.h"
#include "Map.h"
#include "Merge.h"
#include "PartialSum.h"
#include "Overlap.h"
#include "Peek.h"
#include "Recurrence.h"
#include "Repeat.h"
#include "Singleton.h"
#include "Slice.h"
#include "Sort.h"
#include "Stateful.h"
#include "SymmetricDifference.h"
#include "TakeWhile.h"
#include "Union.h"
#include "Zip.h"

#endif
