// Generated by CoffeeScript 1.7.1
(function() {
  var Titles, addSidebarTitle, addToSidebar, makeFunctionSideBarSection, makeLinkSidebarSection;

  Titles = {
    'top': {
      title: 'C++ Streams API',
      link: ''
    },
    'intro': {
      title: 'Introduction',
      link: 'intro'
    },
    'method': {
      title: 'Methods',
      link: 'methods'
    },
    'generator': {
      title: 'Generators',
      link: 'generators'
    },
    'operator.stateless': {
      title: 'Stateless Intermediate Operators',
      link: 'stateless'
    },
    'operator.stateful': {
      title: 'Stateful Intermediate Operators',
      link: 'stateful'
    },
    'terminator': {
      title: 'Terminal Operators',
      link: 'terminals'
    },
    'reducers': {
      title: 'Reducers',
      link: 'reducers'
    },
    'exception': {
      title: 'Exceptions',
      link: 'exceptions'
    },
    'recipes': {
      title: 'Recipes',
      link: 'recipes'
    }
  };

  addSidebarTitle = function($sidebar, cls) {
    var title;
    title = $("<a/>");
    title.addClass('sidebar-title');
    title.attr('href', '#' + Titles[cls].link);
    title.html(Titles[cls].title);
    return $sidebar.append(title);
  };

  addToSidebar = function($list, $func) {
    var $anchor, $item, id;
    id = $func.attr('id');
    $item = $('<li/>');
    $item.addClass('sidebar-item');
    $anchor = $('<a/>');
    $anchor.addClass('sidebar-anchor');
    $anchor.html($('.fname', $func).html());
    $anchor.attr('href', '#' + id);
    $item.append($anchor);
    return $list.append($item);
  };

  makeLinkSidebarSection = function($sidebar, cls) {
    return addSidebarTitle($sidebar, cls);
  };

  makeFunctionSideBarSection = function($sidebar, cls) {
    var $list;
    addSidebarTitle($sidebar, cls);
    $list = $('<ul/>');
    $list.addClass("sidebar-list");
    $(".function." + cls).each(function(index, el) {
      return addToSidebar($list, $(el));
    });
    return $sidebar.append($list);
  };

  $(function() {
    var $sidebar;
    $sidebar = $('#sidebar');
    makeLinkSidebarSection($sidebar, 'top');
    makeLinkSidebarSection($sidebar, 'intro');
    makeFunctionSideBarSection($sidebar, 'method');
    makeFunctionSideBarSection($sidebar, 'generator');
    makeFunctionSideBarSection($sidebar, 'operator.stateless');
    makeFunctionSideBarSection($sidebar, 'operator.stateful');
    makeFunctionSideBarSection($sidebar, 'terminator');
    makeFunctionSideBarSection($sidebar, 'reducers');
    makeFunctionSideBarSection($sidebar, 'exception');
    return makeLinkSidebarSection($sidebar, 'recipes');
  });

}).call(this);
